# Generated by Django 3.0.8 on 2020-08-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exam',
            table=None,
        ),
    ]
